# Generated by Django 5.1.6 on 2025-03-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_coursegrade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examalert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studybreaktimer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studychallenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studynote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyplanadjustment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyreflection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studystatistic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studytaskpriority',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studytracker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subjectsuggestion',
            name='user',
        ),
    ]
