# Generated by Django 5.1.6 on 2025-03-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_remove_coursegrade_user_remove_examalert_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogress',
            name='duration',
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='study_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studyschedule',
            name='study_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studytracker',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
