# Generated by Django 5.1.6 on 2025-03-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_studyprogress_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studyprogress',
            name='study_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studyschedule',
            name='study_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studytracker',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
